import type { AppSnapshot } from './contracts.js'
import { STATE_SCHEMA_VERSION } from './contracts.js'
import { DEFAULT_HOTKEYS } from './types.js'

export function createDefaultSnapshot(): AppSnapshot {
  return {
    schemaVersion: STATE_SCHEMA_VERSION,
    documents: [],
    activeDocumentId: null,
    scrollPosition: 0,
    scrollSpeed: 60,
    playing: false,
    playbackSessionId: null,
    overlayVisible: true,
    voiceStatus: 'off',
    voiceError: null,
    opacity: 0.85,
    bgDim: 0.4,
    fontSize: 48,
    fontFamily: 'Inter, system-ui, sans-serif',
    fontColor: '#ffffff',
    textShadow: true,
    mirrorH: false,
    mirrorV: false,
    eyeLinePosition: 0.4,
    showEyeLine: true,
    focusMode: false,
    clickThrough: false,
    hideFromCapture: false,
    voicePacing: false,
    markdown: false,
    bannerMode: false,
    bannerPosition: 'bottom',
    editMode: false,
    clickerMode: false,
    clickerStep: 0.05,
    showChronometer: true,
    voiceConsent: false,
    countdownEnabled: false,
    countdownSeconds: 3,
    showCueHud: false,
    drivePresentation: false,
    aboveFullscreen: false,
    targetMode: null,
    targetDurationSec: null,
    targetWpm: null,
    hotkeyBindings: { ...DEFAULT_HOTKEYS },
    recentFiles: [],
    overlayBounds: { x: 100, y: 100, width: 900, height: 600 },
    controlsBounds: { x: 80, y: 80, width: 1100, height: 760 },
  }
}
